# Generated by Django 5.1.2 on 2024-10-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anagraphicUniquePatientID', models.CharField(max_length=150, unique=True)),
                ('anagraphicSurname', models.CharField(help_text='<i>(Cognome del paziente)</i>', max_length=50, verbose_name='Cognome')),
                ('anagraphicName', models.CharField(help_text='<i>(Nome del paziente)</i>', max_length=50, verbose_name='Nome')),
                ('anagraphicBirthdate', models.DateField(help_text='<i>gg/mm/yyyy</i>', verbose_name='Data di nascita')),
                ('anagraphicGender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10, verbose_name='Genere')),
                ('intraoperativaSide', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('B', 'Bilateral')], max_length=1)),
                ('intraoperativaDate', models.DateField()),
                ('intraoperativaSurgeon', models.CharField(choices=[('BE', 'Brunocilla'), ('SR', 'Schiavina'), ('BL', 'Bianchi'), ('CF', 'Chessa')], max_length=20)),
            ],
        ),
    ]
