# Generated by Django 4.2.16 on 2024-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidney_robotic', '0002_remove_patient_anagraphicuniquepatientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='anagraphicBirthdate',
            field=models.DateField(help_text='<br><br>', verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anagraphicGender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], help_text='<br><br>', max_length=10, verbose_name='Genere'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anagraphicName',
            field=models.CharField(help_text='<i>(Nome del paziente)</i><br><br>', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anagraphicSurname',
            field=models.CharField(help_text='<i>(Cognome del paziente)</i><br><br>', max_length=50, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='intraoperativaDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='intraoperativaSide',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('B', 'Bilateral')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='intraoperativaSurgeon',
            field=models.CharField(choices=[('BE', 'Brunocilla'), ('SR', 'Schiavina'), ('BL', 'Bianchi'), ('CF', 'Chessa')], max_length=20, null=True),
        ),
    ]
